# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-03 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0011_auto_20190714_2159'),
        ('seed', '0114_auto_20191202_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='HELIXGreenAssessment',
            fields=[
                ('greenassessment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seed.GreenAssessment')),
                ('is_reso_certification', models.BooleanField(default=True)),
            ],
            bases=('seed.greenassessment',),
        ),
        migrations.CreateModel(
            name='HELIXGreenAssessmentProperty',
            fields=[
                ('greenassessmentproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seed.GreenAssessmentProperty')),
                ('opt_out', models.BooleanField(default=False)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('seed.greenassessmentproperty',),
        ),
        migrations.CreateModel(
            name='HelixMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.CharField(choices=[('PROD', 'Production'), ('CONS', 'Consumption'), ('COST', 'Cost'), ('SAVE', 'Savings'), ('EMIT', 'Emissions'), ('CAP', 'Capacity')], max_length=4)),
                ('measurement_subtype', models.CharField(blank=True, choices=[('PV', 'Photovoltaics'), ('WIND', 'Wind')], max_length=15, null=True)),
                ('fuel', models.CharField(choices=[('ELEC', 'Electric'), ('NATG', 'Natural Gas'), ('FUEL', 'Fuel Oil'), ('PROP', 'Propane'), ('CWOOD', 'Cord Wood'), ('PWOOD', 'Pellet Wood')], max_length=5)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('KWH', 'Kilowatt Hours'), ('KW', 'Kilowatt'), ('GAL', 'Gallon'), ('MMBTU', 'mmbtu'), ('TON', 'ton'), ('LB', 'pound'), ('CORD', 'cord'), ('THERM', 'therm'), ('DOLLAR', 'dollars'), ('GHG', 'Greenhouse Gas'), ('CO2e', 'Carbon Dioxide Equivalent')], max_length=5)),
                ('status', models.CharField(choices=[('ACTUAL', 'Actual'), ('ESTIMATE', 'Estimated'), ('PART_ESTIMATE', 'Partially Estimated')], max_length=13)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('assessment_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='seed.GreenAssessmentProperty')),
            ],
        ),
        migrations.CreateModel(
            name='HELIXOrganization',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orgs.Organization')),
                ('hes', models.CharField(blank=True, max_length=100, null=True)),
                ('hes_start_date', models.DateField(blank=True, null=True)),
                ('hes_end_date', models.DateField(blank=True, null=True)),
                ('hes_partner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hes_partner_password', models.CharField(blank=True, max_length=100, null=True)),
                ('leed_start_date', models.DateField(blank=True, null=True)),
                ('leed_end_date', models.DateField(blank=True, null=True)),
                ('leed_geo_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('orgs.organization',),
        ),
        migrations.CreateModel(
            name='HELIXPropertyMeasure',
            fields=[
                ('propertymeasure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seed.PropertyMeasure')),
                ('current_financing', models.CharField(blank=True, choices=[('LEASE', 'Leased Renewables'), ('PPA', 'Power Purchase Agreement'), ('PACE', 'Property-Assessed Clean Energy')], max_length=5, null=True)),
                ('ownership', models.CharField(blank=True, choices=[('OWN', 'Seller Owned'), ('3RD', 'Third-Party Owned')], max_length=3, null=True)),
                ('electric', models.CharField(blank=True, choices=[('NETMETER', 'Net Meter'), ('STORAGE', 'Energy Storage Device'), ('RENEWWIRED', 'Pre-Wired for Renewables'), ('RENEWREADY', 'Ready for Renewables')], max_length=10, null=True)),
                ('installer', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, choices=[('ADMIN', 'Administrator'), ('ASSES', 'Assessor'), ('BILDR', 'Builder'), ('CONTR', 'Contractor/Installer'), ('OTH', 'Other'), ('OWN', 'Owner'), ('SPNSR', 'Program Sponsor'), ('VERIF', 'Program Verifier'), ('PUBRE', 'Public Records')], max_length=5, null=True)),
            ],
            bases=('seed.propertymeasure',),
        ),
        migrations.AddField(
            model_name='helixmeasurement',
            name='measure_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='seed.PropertyMeasure'),
        ),
    ]
