# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-13 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20160412_1123'),
        ('helix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HELIXOrganization',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orgs.Organization')),
                ('hes', models.CharField(blank=True, max_length=100, null=True)),
                ('hes_start_date', models.DateField(blank=True, null=True)),
                ('hes_end_date', models.DateField(blank=True, null=True)),
            ],
            bases=('orgs.organization',),
        ),
    ]
