# Generated by Django 2.2.10 on 2020-04-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helixmeasurement',
            name='unit',
            field=models.CharField(choices=[('KWH', 'Kilowatt Hours per Year'), ('KW', 'Kilowatt'), ('GAL', 'Gallon'), ('MMBTU', 'mmbtu'), ('TON', 'ton'), ('LB', 'pound'), ('CORD', 'cord'), ('THERM', 'therm'), ('DOLLAR', 'dollars'), ('GHG', 'Greenhouse Gas'), ('CO2e', 'Carbon Dioxide Equivalent')], max_length=5),
        ),
    ]
