# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-23 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helix', '0005_auto_20180605_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='helixorganization',
            name='leed_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helixorganization',
            name='leed_geo_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='helixorganization',
            name='leed_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
