# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-12 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('tos', '0001_initial'),
        ('helix', '0006_auto_20180823_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='HELIXTermsOfService',
            fields=[
                ('termsofservice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tos.TermsOfService')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='auth.Group')),
            ],
            options={
                'abstract': False,
            },
            bases=('tos.termsofservice',),
        ),
    ]
