# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-20 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0094_merge_20180917_0657'),
        ('helix', '0007_helixtermsofservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HELIXPropertyMeasure',
            fields=[
                ('propertymeasure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='seed.PropertyMeasure')),
                ('current_financing', models.CharField(blank=True, choices=[(b'LEASE', b'Leased Renewables'), (b'PPA', b'Power Purchase Agreement'), (b'PACE', b'Property-Assessed Clean Energy')], max_length=5, null=True)),
                ('electric', models.CharField(blank=True, choices=[(b'NETMETER', b'Net Meter'), (b'STORAGE', b'Energy Storage Device'), (b'PVOWN', b'Photovoltaics Seller Owned'), (b'PV3RD', b'Photovoltaics Third-Party Owned'), (b'WINDOWN', b'Wind Turbine Seller Owned'), (b'WIND3RD', b'Wind Turbine Third-Party Owned'), (b'RENEWWIRE', b'Pre-Wired for Renewables'), (b'RENEWREADY', b'Ready for Renewables')], max_length=10, null=True)),
                ('installer', models.CharField(blank=True, choices=[(b'NETMETER', b'Net Meter'), (b'STORAGE', b'Energy Storage Device'), (b'PVOWN', b'Photovoltaics Seller Owned'), (b'PV3RD', b'Photovoltaics Third-Party Owned'), (b'WINDOWN', b'Wind Turbine Seller Owned'), (b'WIND3RD', b'Wind Turbine Third-Party Owned'), (b'RENEWWIRE', b'Pre-Wired for Renewables'), (b'RENEWREADY', b'Ready for Renewables')], max_length=10, null=True)),
            ],
            bases=('seed.propertymeasure',),
        ),
    ]
