# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-22 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helix', '0008_helixpropertymeasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='helixmeasurement',
            name='measures_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='helix.HELIXPropertyMeasure'),
        ),
        migrations.AlterField(
            model_name='helixmeasurement',
            name='assessment_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='seed.GreenAssessmentProperty'),
        ),
        migrations.AlterField(
            model_name='helixpropertymeasure',
            name='electric',
            field=models.CharField(blank=True, choices=[(b'NETMETER', b'Net Meter'), (b'STORAGE', b'Energy Storage Device'), (b'PVOWN', b'Photovoltaics Seller Owned'), (b'PV3RD', b'Photovoltaics Third-Party Owned'), (b'WINDOWN', b'Wind Turbine Seller Owned'), (b'WIND3RD', b'Wind Turbine Third-Party Owned'), (b'RENEWWIRED', b'Pre-Wired for Renewables'), (b'RENEWREADY', b'Ready for Renewables')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='helixpropertymeasure',
            name='installer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
