# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seed', '0094_merge_20180917_0657'),
        ('helix', '0009_auto_20181222_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helixmeasurement',
            name='measures_property',
        ),
        migrations.AddField(
            model_name='helixmeasurement',
            name='measure_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='seed.PropertyMeasure'),
        ),
    ]
