# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-07 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helix', '0011_helixpropertymeasure_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='helixpropertymeasure',
            name='ownership',
            field=models.CharField(blank=True, choices=[(b'OWN', b'Seller Owned'), (b'3RD', b'Third-Party Owned')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='helixpropertymeasure',
            name='electric',
            field=models.CharField(blank=True, choices=[(b'NETMETER', b'Net Meter'), (b'STORAGE', b'Energy Storage Device'), (b'RENEWWIRED', b'Pre-Wired for Renewables'), (b'RENEWREADY', b'Ready for Renewables')], max_length=10, null=True),
        ),
    ]
