# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-12 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helix', '0012_auto_20190207_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='helixpropertymeasure',
            name='source',
            field=models.CharField(blank=True, choices=[(b'ADMIN', b'Administrator'), (b'ASSES', b'Assessor'), (b'BILDR', b'Builder'), (b'CONTR', b'Contractor/Installer'), (b'OTH', b'Other'), (b'OWN', b'Owner'), (b'SPNSR', b'Program Sponsor'), (b'VERIF', b'Program Verifier'), (b'PUBRE', b'Public Records')], max_length=5, null=True),
        ),
    ]
