# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-26 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helix', '0013_helixpropertymeasure_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helixmeasurement',
            name='fuel',
            field=models.CharField(choices=[(b'ELEC', b'Electric'), (b'NATG', b'Natural Gas'), (b'HEAT', b'Fuel Oil'), (b'PROP', b'Propane'), (b'CWOOD', b'Cord Wood'), (b'PWOOD', b'Pellet Wood')], max_length=5),
        ),
        migrations.AlterField(
            model_name='helixmeasurement',
            name='measurement_type',
            field=models.CharField(choices=[(b'PROD', b'Production'), (b'CONS', b'Consumption'), (b'COST', b'Cost'), (b'SAVE', b'Savings'), (b'EMIT', b'Emissions'), (b'CAP', b'Capacity')], max_length=4),
        ),
    ]
